export type UserType = 'profissional' | 'paciente';

export type MockAccount = {
  name: string;
  email: string;
  password: string;
  type: UserType;
  patientId?: string;
  monitoringStatus?: string;
};

export const MOCK_ACCOUNTS: MockAccount[] = [
  {
    name: 'Dr. Carlos Mendes',
    email: 'profissional@teste.com',
    password: '123456',
    type: 'profissional',
  },
  {
    name: 'Carlos Alberto Silva',
    email: 'carlos.alberto@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-001',
    monitoringStatus: 'Ativo',
  },
  {
    name: 'Mariana Souza Santos',
    email: 'mariana.santos@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-002',
    monitoringStatus: 'Estável',
  },
  {
    name: 'Roberto Ferreira Lima',
    email: 'roberto.lima@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-003',
    monitoringStatus: 'Alerta',
  },
  {
    name: 'Ana Beatriz Oliveira',
    email: 'ana.beatriz@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-004',
    monitoringStatus: 'Ativo',
  },
  {
    name: 'Ricardo Mendes Vaz',
    email: 'ricardo.vaz@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-005',
    monitoringStatus: 'Em repouso',
  },
  {
    name: 'Juliana Costa Paiva',
    email: 'juliana.paiva@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-006',
    monitoringStatus: 'Estável',
  },
  {
    name: 'Fernando Gomes',
    email: 'fernando.gomes@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-007',
    monitoringStatus: 'Ativo',
  },
  {
    name: 'Beatriz Martins',
    email: 'beatriz.martins@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-008',
    monitoringStatus: 'Alerta',
  },
  {
    name: 'Lucas Henrique Rocha',
    email: 'lucas.rocha@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-009',
    monitoringStatus: 'Ativo',
  },
  {
    name: 'Camila Rodrigues',
    email: 'camila.rod@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-010',
    monitoringStatus: 'Estável',
  },
  {
    name: 'Gabriel Antunes',
    email: 'gabriel.ant@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-011',
    monitoringStatus: 'Em repouso',
  },
  {
    name: 'Larissa Cavalcante',
    email: 'larissa.c@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-012',
    monitoringStatus: 'Alerta',
  },
  {
    name: 'Thiago Montez',
    email: 'thiago.m@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-013',
    monitoringStatus: 'Ativo',
  },
  {
    name: 'Sofia Helena Lima',
    email: 'sofia.h@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-014',
    monitoringStatus: 'Estável',
  },
  {
    name: 'Bruno Espindola',
    email: 'bruno.e@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-015',
    monitoringStatus: 'Ativo',
  },
  {
    name: 'Renata Vasconcelos',
    email: 'renata.v@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-016',
    monitoringStatus: 'Em repouso',
  },
  {
    name: 'Marcos Vinícius',
    email: 'marcos.v@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-017',
    monitoringStatus: 'Alerta',
  },
  {
    name: 'Heloísa Fagundes',
    email: 'heloisa.f@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-018',
    monitoringStatus: 'Estável',
  },
  {
    name: 'Daniel Silveira',
    email: 'daniel.s@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-019',
    monitoringStatus: 'Ativo',
  },
  {
    name: 'Patrícia Amaral',
    email: 'patricia.a@teste.com',
    password: '123456',
    type: 'paciente',
    patientId: '#2026-020',
    monitoringStatus: 'Estável',
  },
];